### ISSUE TITLE
can_logger and can_viewer can not be used on Vector

### ISSUE THREAD

**Issue by xinkunlong** [hardbyte/python-can#1050]
**Describe the bug**
```
(venv) E:\0999_kunlong\python>python -m can.logger -i vector -c 0 -b 500000
Connected to VectorBus: Application CANalyzer: CAN 1
Can Logger (Started on 2021-05-11 23:08:28.021292)
Traceback (most recent call last):
  File "e:\pythoninterpreter\python38-64\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\pythoninterpreter\python38-64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "e:\0999_kunlong\python\python-can\can\logger.py", line 174, in <module>
    main()
  File "e:\0999_kunlong\python\python-can\can\logger.py", line 163, in main
    msg = bus.recv(1)
  File "e:\0999_kunlong\python\python-can\can\bus.py", line 94, in recv
    msg, already_filtered = self._recv_internal(timeout=time_left)
  File "e:\0999_kunlong\python\python-can\can\interfaces\vector\canlib.py", line 383, in _recv_internal
    msg = self._recv_can()
  File "e:\0999_kunlong\python\python-can\can\interfaces\vector\canlib.py", line 457, in _recv_can
    xldriver.xlReceive(self.port_handle, event_count, xl_event)
  File "e:\0999_kunlong\python\python-can\can\interfaces\vector\xldriver.py", line 35, in check_status
    raise VectorError(result, xlGetErrorString(result).decode(), function.__name__)
can.interfaces.vector.exceptions.VectorError: xlReceive failed (XL_ERR_QUEUE_IS_EMPTY)
```

**To Reproduce**
Steps to reproduce the behavior (please add longer code examples below):
```
python -m can.logger -i vector -c 0 -b 500000
```

**Expected behavior**
no error

**Additional context**
```
(venv) E:\0999_kunlong\python>pip show python-can
Name: python-can
Version: 4.0.0.dev2
Summary: Controller Area Network interface module for Python
Home-page: https://github.com/hardbyte/python-can
Author: Python CAN contributors
Author-email: None
License: LGPL v3
Location: e:\0999_kunlong\python\python-can
Requires: wrapt, mypy-extensions, windows-curses, pywin32
Required-by:
OS-version:
Python version:
python-can version:
python-can interface/s:
```

```
HW:VN1630A
```

**Comment by zariiii9003** [comment]
#1025 broke the VectorBus. It resets the error code in the VectorError. Thank you for reporting this.
