### ISSUE TITLE
Bug on notifier

### ISSUE THREAD

**Issue by GiorgioSgl** [hardbyte/python-can#1306]
### Describe the bug
I'm not aware of the actual bug, but the problem is on the notifier

### To Reproduce
```python
def get_leds_connected(initial_timeout=3, channel="can0"):
    leds_id = None

    with can.Bus(interface="socketcan",
                 channel=channel,
                 bitrate=500000,
                 receive_own_messages=False) as b:

        b.send(can.Message(arbitration_id=0, data=[0x01]))

        buffer = can.BufferedReader()

        can.Notifier(bus=b, listeners=[buffer])

        messages = []
        msg = buffer.get_message(timeout=initial_timeout)
        while msg is not None:
            messages.append(msg)
            msg = buffer.get_message()

    return leds_id
```
```bash
Exception in thread can.notifier for bus "socketcan channel 'vcan0'":
Traceback (most recent call last):
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/interfaces/socketcan/socketcan.py", line 526, in capture_message
    cf, ancillary_data, msg_flags, addr = sock.recvmsg(
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/notifier.py", line 122, in _rx_thread
    msg = bus.recv(self.timeout)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/bus.py", line 94, in recv
    msg, already_filtered = self._recv_internal(timeout=time_left)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/interfaces/socketcan/socketcan.py", line 725, in _recv_internal
    msg = capture_message(self.socket, get_channel)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/interfaces/socketcan/socketcan.py", line 534, in capture_message
    raise can.CanOperationError(f"Error receiving: {error.strerror}", error.errno)
can.exceptions.CanOperationError: Error receiving: Bad file descriptor [Error Code 9]
```

### Expected behavior

The notifier should notify the buses but nothing work actually

### Additional context

OS and version: Fedora 35
Python version: python 3.10.4
python-can version: 4.0.0
python-can interface/s (if applicable): vcan0

**Comment by GiorgioSgl** [comment]
> There seems to be a mismatch with the referenced CAN interface:
> 
> `def get_leds_connected(initial_timeout=3, channel="can0"):`
> 
> `Exception in thread can.notifier for bus "socketcan channel 'vcan0'":`

No cause I'm calling the function in this way:
```python
Python 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from integration.can_broadcast import get_leds_connected

In [2]: get_leds_connected(channel="vcan0")

Exception in thread can.notifier for bus "socketcan channel 'vcan0'":
Traceback (most recent call last):
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/interfaces/socketcan/socketcan.py", line 526, in capture_message
    cf, ancillary_data, msg_flags, addr = sock.recvmsg(
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/notifier.py", line 122, in _rx_thread
    msg = bus.recv(self.timeout)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/bus.py", line 94, in recv
    msg, already_filtered = self._recv_internal(timeout=time_left)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/interfaces/socketcan/socketcan.py", line 725, in _recv_internal
    msg = capture_message(self.socket, get_channel)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/interfaces/socketcan/socketcan.py", line 534, in capture_message
    raise can.CanOperationError(f"Error receiving: {error.strerror}", error.errno)
can.exceptions.CanOperationError: Error receiving: Bad file descriptor [Error Code 9]
```

The interface is setup with this script:
```bash
#!/bin/bash
# Make sure the script runs with super user priviliges.
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
# Load the kernel module.
modprobe vcan
# Create the virtual CAN interface.
ip link add dev vcan0 type vcan
# Bring the virutal CAN interface online.
ip link set up vcan0
```

**Comment by GiorgioSgl** [comment]
I try with the version 3.3.4 of the python-can, but still I'm getting a very similar error.

```python
Exception in thread can.notifier for bus "socketcan channel 'vcan0'":
Traceback (most recent call last):
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/interfaces/socketcan/socketcan.py", line 498, in capture_message
    cf = sock.recv(CANFD_MTU)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/notifier.py", line 103, in _rx_thread
    msg = bus.recv(self.timeout)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/bus.py", line 83, in recv
    msg, already_filtered = self._recv_internal(timeout=time_left)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/interfaces/socketcan/socketcan.py", line 621, in _recv_internal
    msg = capture_message(self.socket, get_channel)
  File "/home/giorgiosgl/.local/lib/python3.10/site-packages/can/interfaces/socketcan/socketcan.py", line 501, in capture_message
    raise can.CanError("Error receiving: %s" % exc)
can.CanError: Error receiving: [Errno 9] Bad file descriptor

```

**Comment by GiorgioSgl** [comment]
I fix it.

Actually only need to add a line to stop the notifier at the end.

```python  
with can.Bus(interface="socketcan",
                 channel="can0",
                 receive_own_messages=False) as b:

        buffer = can.BufferedReader()

        notifier = can.Notifier(bus=b, listeners=[buffer]) # I add this

        b.send(can.Message(arbitration_id=0,
                           data=data,
                           is_extended_id=False))

        messages = []
        msg = buffer.get_message(timeout=timeout)
        while msg is not None:
            messages.append(msg)
            msg = buffer.get_message()

        notifier.stop() # and this

    return messages
```
