### ISSUE TITLE
Enhance the error message when requesting file format `.db` with sized rotating logger

### ISSUE THREAD

**Issue by j-c-cook** [hardbyte/python-can#1318]
### Describe the bug

The `can.logger` does not accept `.db` as a format to place the log in, but the API documentation states that `.db` is an acceptable format:
```
    The format is determined from the file suffix which can be one of:
      * .asc: :class:`can.ASCWriter`
      * .blf :class:`can.BLFWriter`
      * .csv: :class:`can.CSVWriter`
      * .db: :class:`can.SqliteWriter`
      * .log :class:`can.CanutilsLogWriter`
      * .txt :class:`can.Printer`
```

### To Reproduce

Enable virtual can: `sudo ip link set vcan0 up type can`
Spam the virtual bus with random can messages 1 ms apart: `cangen vcan0 -e -I 18EAFF26 -L i -v -v -v -g 1`
Log the virtual bus: `python -m can.logger -c vcan0 -i socketcan -b 250000 -f file.db -s 50`

### Expected behavior

The `can.logger` script should successfully log messages. 

### Additional context

OS and version: Ubuntu 20.04.4 LTS
Python version: Python 3.7.17
python-can version: 4.0.0

<details><summary>Traceback and logs</summary>

```python
Traceback (most recent call last):
  File "/home/agco/Documents/python-can/scripts/can_logger.py", line 11, in <module>
    main()
  File "/home/agco/Documents/python-can/can/logger.py", line 206, in main
    base_filename=results.log_file, max_bytes=results.file_size
  File "/home/agco/Documents/python-can/can/io/logger.py", line 322, in __init__
    self._writer = self._get_new_writer(self.base_filename)
  File "/home/agco/Documents/python-can/can/io/logger.py", line 230, in _get_new_writer
    "The Logger corresponding to the arguments is not a FileIOMessageWriter or "
Exception: The Logger corresponding to the arguments is not a FileIOMessageWriter or can.Printer
```
</details>

**Comment by j-c-cook** [comment]
@zariiii9003 I modified the label of this issue. I would not consider this a bug, but rather an enhancement to the error message. I do not have access to change the `label` of this issue.
