### ISSUE TITLE
canplayer doesnt run on windows

### ISSUE THREAD

**Issue by ngavrish** [hardbyte/python-can#145]
I've installed 2.0.0.a2 version and ran

canplayer --help

The output I got was

Traceback (most recent call last):
  File "C:\Users\build-windows\AppData\Local\Programs\Python\Python36\Scripts\canplayer-script.py", line 9, in <module>
    load_entry_point('python-can==2.0.0a2', 'console_scripts', 'canplayer')()
  File "c:\users\build-windows\downloads\python-can-develop\python-can-develop\can\io\player.py", line 104, in main
    choices=can.interface.VALID_INTERFACES)
AttributeError: module 'can.interface' has no attribute 'VALID_INTERFACES'

**Comment by christiansandberg** [comment]
Thanks! I think it's fixed now.

Try installing the develop branch:
`$ pip install --upgrade https://github.com/hardbyte/python-can/archive/develop.zip`
