### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by catmemo** [hardbyte/python-can#1542]
### Describe the bug
Dears, I created a bus as below (bitrate is 500000, channel is 0):
```
 if bustype == "pcan":
          channel = 'PCAN_USBBUS' + str(channel+1)
          bus = can.interface.Bus(bustype=bustype, channel=channel, bitrate=bitrate)
```

and this is the error I receive:
```
Traceback (most recent call last):
  File "D:\Development_Tasks\CANSimulator\gui.py", line 1259, in start_can_bus_operation
    dpg.get_value(self.response_id))
  File "D:\Development_Tasks\CANSimulator\send_diag_request.py", line 160, in __init__
    bus = can.interface.Bus(bustype=bustype, channel=channel, bitrate=bitrate)
  File "D:\Development_Tools\Python\lib\site-packages\can\interface.py", line 120, in __new__
    bus = cls(channel, *args, **kwargs)
  File "D:\Development_Tools\Python\lib\site-packages\can\interfaces\pcan\pcan.py", line 212, in __init__
    self.m_objPCANBasic = PCANBasic()
  File "D:\Development_Tools\Python\lib\site-packages\can\interfaces\pcan\basic.py", line 661, in __init__
    self.__m_dllBasic = windll.LoadLibrary("PCANBasic")
  File "D:\Development_Tools\Python\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "D:\Development_Tools\Python\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
I have already use the PCAN in PCAN-Explore5 and it works well. And then I close the PCAN-Explore5 and tried to use it with python-can, but failed.
Could anyone help to check? Thks in advance!
### To Reproduce
Please refer to above.

### Expected behavior
Make the PCAN can work successfully

### Additional context

OS and version: Win10
Python version: 3.7.2
python-can version: 4.0.0
python-can interface/s (if applicable):

**Comment by catmemo** [comment]
Refer to #759
