### ISSUE TITLE
Issues with UdpMulticastBus and MacOS

### ISSUE THREAD

**Issue by jmailloux** [hardbyte/python-can#1760]
### Describe the bug
There are 2 issues with UdpMulticastBus and MacOS.
First one is once one process opened the socket, another process could not.  This made having one process send messages and another receive them on the same computer problematic.  Doing this:
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1) fixed that problem.
The second one was reading timestamps with SIOCGSTAMP didn't work - MacOS doesn't support that ioctl.  I don't know how to fix that one.  I just removed it and replaced the timestamp with a sequence number instead.

### To Reproduce
Try to set up a UdpMulticastBus interface on 2 processes on MacOS (v14.4)

### Expected behavior
Able to set up multiple UdpMulticastBus interfaces on multiple processes on same computer

### Additional context

OS and version: MacOS 14.4
Python version: 3.12.2
python-can version: main
python-can interface/s (if applicable): UdpMulticastBus

I have code to address these issues - I can submit a pull request if desired.

<details><summary>Traceback and logs</summary>

import can

def receive_messages():
    # Configure the bus with the multicast group and port
    bus = can.Bus(interface='udp_multicast', channel='239.0.0.1', port=10000, receive_own_messages=False)

    print(f"Listening for messages...")
    while True:
        message = bus.recv()  # Block until a message is received
        if message:
            print(f"Received: {message}")

if __name__ == '__main__':
    receive_messages()

**Comment by dennis-glx** [comment]
Could you please suggest where to make this change as a temporary fix? 

python-can version = 4.5.0
macos-version = 15.3.1

For example, adding the port re-use option to  ```can/interfaces/udp_multicast/bus.py``` line 270 gives me this exception. 

```python
# Sender Process
import can

bus = can.interface.Bus(
    interface="udp_multicast",
    channel="224.0.0.1",  # IPv4 multicast group
    port=20001,
)

msg = can.Message(arbitration_id=0x123, data=[1, 2, 3, 4], is_extended_id=False)
bus.send(msg)

bus.shutdown()

# Receiver Process
import can

bus = can.interface.Bus(
    interface="udp_multicast",
    channel="224.0.0.1",  # Same group
    port=20001,
)

while True:
    msg = bus.recv()
    if msg:
        print(f"Received: {msg}")
```

```bash
# Sender exits cleanly, but I get this exception from receiver on receipt. 

Traceback (most recent call last):
  File "/Users/dennisjohnson/test_udp_multicast/receive.py", line 10, in <module>
    msg = bus.recv()
  File "/Users/dennisjohnson/.venv/lib/python3.10/site-packages/can/bus.py", line 127, in recv
    msg, already_filtered = self._recv_internal(timeout=time_left)
  File "/Users/dennisjohnson/.venv/lib/python3.10/site-packages/can/interfaces/udp_multicast/bus.py", line 127, in _recv_internal
    result = self._multicast.recv(timeout)
  File "/Users/dennisjohnson/.venv/lib/python3.10/site-packages/can/interfaces/udp_multicast/bus.py", line 391, in recv
    result_buffer = ioctl(
OSError: [Errno 6] Device not configured
UdpMulticastBus was not properly shut down
```
