### ISSUE TITLE
Tests fail on Python 2.7

### ISSUE THREAD

**Issue by jluttine** [hardbyte/python-can#699]
I'm trying to install the most recent version from PyPI (3.3.1) and run tests for that:
```
Traceback (most recent call last):
  File "/nix/store/xj6c66ah627h5793hdm9jwlbdqphk7mp-python2.7-pytest-4.6.5/bin/.pytest-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/xj6c66ah627h5793hdm9jwlbdqphk7mp-python2.7-pytest-4.6.5/lib/python2.7/site-packages/_pytest/config/__init__.py", line 63, in main
    config = _prepareconfig(args, plugins)
  File "/nix/store/xj6c66ah627h5793hdm9jwlbdqphk7mp-python2.7-pytest-4.6.5/lib/python2.7/site-packages/_pytest/config/__init__.py", line 207, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/nix/store/ma5id8c9gjjdh5qa990bl8kj16nl87xm-python2.7-pluggy-0.12.0/lib/python2.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/nix/store/ma5id8c9gjjdh5qa990bl8kj16nl87xm-python2.7-pluggy-0.12.0/lib/python2.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/nix/store/ma5id8c9gjjdh5qa990bl8kj16nl87xm-python2.7-pluggy-0.12.0/lib/python2.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/nix/store/ma5id8c9gjjdh5qa990bl8kj16nl87xm-python2.7-pluggy-0.12.0/lib/python2.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/nix/store/xj6c66ah627h5793hdm9jwlbdqphk7mp-python2.7-pytest-4.6.5/lib/python2.7/site-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/nix/store/ma5id8c9gjjdh5qa990bl8kj16nl87xm-python2.7-pluggy-0.12.0/lib/python2.7/site-packages/pluggy/callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "/nix/store/ma5id8c9gjjdh5qa990bl8kj16nl87xm-python2.7-pluggy-0.12.0/lib/python2.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/nix/store/xj6c66ah627h5793hdm9jwlbdqphk7mp-python2.7-pytest-4.6.5/lib/python2.7/site-packages/_pytest/config/__init__.py", line 687, in pytest_cmdline_parse
    self.parse(args)
  File "/nix/store/xj6c66ah627h5793hdm9jwlbdqphk7mp-python2.7-pytest-4.6.5/lib/python2.7/site-packages/_pytest/config/__init__.py", line 895, in parse
    self._preparse(args, addopts=addopts)
  File "/nix/store/xj6c66ah627h5793hdm9jwlbdqphk7mp-python2.7-pytest-4.6.5/lib/python2.7/site-packages/_pytest/config/__init__.py", line 841, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/nix/store/ma5id8c9gjjdh5qa990bl8kj16nl87xm-python2.7-pluggy-0.12.0/lib/python2.7/site-packages/pluggy/manager.py", line 292, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/nix/store/fm79x0al39c60d1q31803in3rmpai3fs-python2.7-importlib-metadata-0.18/lib/python2.7/site-packages/importlib_metadata/__init__.py", line 90, in load
    module = import_module(match.group('module'))
  File "/nix/store/ws28m49kdhyrx4x68rx3sxi1nwrc6dy1-python-2.7.16/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/nix/store/m6xdfcr0n1cw631njzwbyvq26072bk33-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/__init__.py", line 26, in <module>
    from hypothesis._settings import settings, Verbosity, Phase, HealthCheck, unlimited
  File "/nix/store/xj6c66ah627h5793hdm9jwlbdqphk7mp-python2.7-pytest-4.6.5/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 304, in load_module
    exec(co, mod.__dict__)
  File "/nix/store/m6xdfcr0n1cw631njzwbyvq26072bk33-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/_settings.py", line 40, in <module>
    from hypothesis.internal.compat import string_types
  File "/nix/store/xj6c66ah627h5793hdm9jwlbdqphk7mp-python2.7-pytest-4.6.5/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 304, in load_module
    exec(co, mod.__dict__)
  File "/nix/store/m6xdfcr0n1cw631njzwbyvq26072bk33-python2.7-hypothesis-4.7.3/lib/python2.7/site-packages/hypothesis/internal/compat.py", line 302, in <module>
    typing_root_type = (typing._Final, typing._GenericAlias)  # type: ignore
AttributeError: 'module' object has no attribute '_GenericAlias'
```

I have `typing` version 3.7.4.1.

I also tried using version 3.3.2 from GitHub but then I get the following error:
```
ERROR: python-can requires Python '>=3.6' but the running Python is 2.7.16
```
But README says that library version 3.x supports Python 2.7+ (and 3.5+). So there should be support based on README.

**Comment by jluttine** [comment]
Oh, the tests failed because of too old `hypothesis` package. Now they work. But I'm still wondering about the Python 2 support in 3.3.2 though..
