### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by skywo1f** [hardbyte/python-can#801]
pi@raspberrypi:~/utils/python-can/examples $ ./receive_all.py 
Traceback (most recent call last):
  File "./receive_all.py", line 7, in <module>
    import can
  File "/usr/local/lib/python2.7/dist-packages/python_can-3.2.0-py2.7.egg/can/__init__.py", line 13
    rc: Dict[str, Any] = dict()
      ^
SyntaxError: invalid syntax

**Comment by christiansandberg** [comment]
Python 2.7 is not supported anymore. Please use 3.6 or later.
