### ISSUE TITLE
error using multiple Vector devices

### ISSUE THREAD

**Issue by danielhrisca** [hardbyte/python-can#971]
The setup contains 2 Vector devices and a CAN cable that connects the ECU and the 2 boxes (using the first piggy on each device):
* Vector Vn1630A
* Vector VH6501

``CANoe CAN1`` is assigned to the first piggy of the VH6501 device. 

If I assign ``MyAPP CAN1`` to the same piggy then I can record the traffic.
If I assign ``MyAPP CAN1`` to the first piggy of VN1630A then I get the following error:

```
Details: Traceback (most recent call last):
  File "MyAPP\xil\devices\can_device.py", line 276, in prepare
  File "lib\site-packages\can\util.py", line 303, in wrapper
  File "lib\site-packages\can\interfaces\vector\canlib.py", line 183, in __init__
  File "lib\site-packages\can\interfaces\vector\canlib.py", line 686, in get_application_config
  File "lib\site-packages\can\interfaces\vector\xldriver.py", line 35, in check_status
can.interfaces.vector.exceptions.VectorError: xlGetApplConfig failed (XL_ERROR)
```

Any idea about what is going on here?

**Comment by zariiii9003** [comment]
Hello Daniel,

can you find the channel in `vector.canlib.get_channel_configs()`?

The function call 
```python
xldriver.xlGetApplConfig(
    app_name.encode(),
    app_channel,
    hw_type,
    hw_index,
    hw_channel,
    xldefine.XL_BusTypes.XL_BUS_TYPE_CAN,
)
```
is pretty straightforward, i have no clue how it could cause an error
